#!/bin/bash

set -euo pipefail

manifest_generate() {
  local target_dir="${1:-.}"

  [ -d "$target_dir" ] || die "Directory does not exist: $target_dir"

  local out="$target_dir/orchestra-source.yaml"

  if [ -f "$out" ]; then
    if ! ask_overwrite "$out"; then
      log_info "Skipped."
      return 0
    fi
  fi

  {
    echo "# Orchestra source manifest — generated by 'orchestra generate-manifest'"
    echo "# Fields per package: name, type, path"
    echo "# Types: agent | prompt | prompt-dir | skill"
    echo ""
    echo "packages:"

    local has_agents=0
    if [ -d "$target_dir/agents" ]; then
      local files=()
      while IFS= read -r f; do
        files+=("$f")
      done < <(find "$target_dir/agents" -maxdepth 1 -name '*.agent.md' -type f | sort)
      if [ ${#files[@]} -gt 0 ]; then
        echo "  # --- Agents ---"
        for f in "${files[@]}"; do
          local name rel
          name="$(basename "$f" .agent.md)"
          rel="${f#$target_dir/}"
          printf '  - name: %s\n    type: agent\n    path: %s\n' "$name" "$rel"
        done
        echo ""
        has_agents=1
      fi
    fi

    local has_prompts=0
    if [ -d "$target_dir/prompts" ]; then
      local files=()
      while IFS= read -r f; do
        files+=("$f")
      done < <(find "$target_dir/prompts" -maxdepth 1 -name '*.prompt.md' -type f | sort)
      if [ ${#files[@]} -gt 0 ]; then
        echo "  # --- Prompts ---"
        for f in "${files[@]}"; do
          local name rel
          name="$(basename "$f" .prompt.md)"
          rel="${f#$target_dir/}"
          printf '  - name: %s\n    type: prompt\n    path: %s\n' "$name" "$rel"
        done
        echo ""
        has_prompts=1
      fi

      if [ -d "$target_dir/prompts/snippets" ]; then
        echo "  # --- Prompt snippets (multi-file package) ---"
        printf '  - name: snippets\n    type: prompt-dir\n    path: prompts/snippets/\n'
        echo ""
      fi
    fi

    local has_skills=0
    if [ -d "$target_dir/skills" ]; then
      local dirs=()
      while IFS= read -r d; do
        [ -f "$d/SKILL.md" ] || continue
        dirs+=("$d")
      done < <(find "$target_dir/skills" -maxdepth 1 -mindepth 1 -type d | sort)
      if [ ${#dirs[@]} -gt 0 ]; then
        echo "  # --- Skills ---"
        for d in "${dirs[@]}"; do
          local name rel
          name="$(basename "$d")"
          rel="${d#$target_dir/}"
          printf '  - name: %s\n    type: skill\n    path: %s/\n' "$name" "$rel"
        done
        echo ""
        has_skills=1
      fi
    fi

    if [ $has_agents -eq 0 ] && [ $has_prompts -eq 0 ] && [ $has_skills -eq 0 ]; then
      echo "  # (no agents/, prompts/, or skills/ directories with valid content were found in $target_dir)"
    fi
  } > "$out"

  log_info "Generated $out"
  local pkg_count
  pkg_count=$(yaml_manifest_count "$out")
  echo "  Packages: $pkg_count"
}